name: build
run-name: ${{ github.actor }} is building the gradle project
on: [push]
jobs:
  build-main-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version-file: ./sonar/.java-version
          distribution: temurin
          cache: gradle
      - run: cd sonar && ./gradlew build --no-daemon
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            sonar/build/test-results/test/*.xml
      - name: Sonarlint
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sonar/build/reports/sonarlint/sonarlintMain.sarif
          category: Sonarlint
      - name: Spotbugs
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sonar/build/reports/spotbugs/main.sarif
          category: Spotbugs
      - name: Archive main artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: sonar/build/libs
